#!/bin/bash

clear
echo -e "
  ____             _       ____ _____ 
 |  _ \ ___  _   _| |_ ___| ___|___ / 
 | |_) / _ \| | | | __/ _ \___ \ |_ \ 
 |  _ < (_) | |_| | ||  __/___) |__) |
 |_| \_\___/ \__,_|\__\___|____/____/ 
                                      

"
aws route53 create-hosted-zone --name $1 --delegation-set-id  N3J3ITYEBIRAJ1 --caller-reference  "`date +%d%m%y%l%M`" --hosted-zone-config Comment="$1" > out.txt





id=$(cat out.txt | grep Location | cut -d "/" -f6 | cut -d '"' -f1| grep -oP '\b[A-Z0-9]+\b')
if [[ -z $id ]]
then
echo -e "\n-> \e[31m\e[1mZone not Created\e[0m"
exit 1
else
echo -e "\n-> \e[32m\e[1mZone Created\e[0m"
echo -e "\n-> Creating DNS record for $1"
sed s/thisisatest.in/$1/g record.json > $1.json
sed -i s/1.1.1.1/$2/g $1.json





aws route53 change-resource-record-sets --hosted-zone-id $id --change-batch file://$1.json > out.txt
dns_status=$(cat out.txt | grep PENDING)
if [[ -z $dns_status ]]
then
echo -e "\n-> \e[31m\e[1mDNS record not Created\e[0m"
exit 0
else
echo -e "\n-> \e[32m\e[1mDNS record Created\e[0m"
rm -f out.txt $1.json
fi
fi
